name: Viestinvalityspalvelu deploy workflow
permissions:
  id-token: write
  contents: read
on:
  workflow_dispatch:
    inputs:
      build-number:
        type: number
        description: Github Actions build number
      environment:
        type: choice
        description: Environment where to deploy
        options:
          - untuva
          - hahtuva
          - pallero
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        if: ${{ inputs.environment == 'hahtuva' || inputs.environment == 'untuva' || inputs.environment == 'pallero' }}
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4
        with:
          role-to-assume: ${{ secrets.AWS_OPINTOPOLKU_DEV_ROLE_ARN }}
          role-session-name: viestinvalityspalvelu-deploy
          aws-region: eu-west-1