name: Deploy viestinvalityspalvelu client library
on:
  workflow_dispatch:
  release:
    types: [ created ]
  push:
    paths-ignore:
      - '**.md'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: 'maven'

      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./mvnw --no-transfer-progress clean package
        working-directory: viestinvalityspalvelu

  deploy-client-library:
    needs: [ build-and-test ]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: 'maven'

      - name: Deploy Client Library
        #if: ${{ success() && format('refs/heads/{0}', github.event.repository.default_branch) == github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./mvnw deploy --batch-mode -DskipTests --projects kirjasto --also-make
        working-directory: viestinvalityspalvelu
